# Generated by Django 3.1.7 on 2021-07-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210723_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comment_number',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='like_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
